spring.application.name=tradesphere

server.port=8080

spring.data.mongodb.uri=${mongodb+srv://<db_username>:zWo73zgaYbXHngPR@tradesphere.r6p0nou.mongodb.net/?appName=tradesphere}
spring.data.mongodb.database=test

# JWT
jwt.secret=${JWT_SECRET:change-this-development-secret-key-change-this-development-secret-key}
jwt.expiration-ms=3600000

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.tradesphere=INFO