spring.application.name=tradesphere

spring.data.mongodb.uri=mongodb://localhost:27017/tradesphere
spring.data.mongodb.database=tradesphere

# JWT configuration
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=3600000